package com.lostpetfinder.entity;

public enum CategoryEnum {
    LJUBIMAC_JE_NESTAO_I_ZA_NJIM_SE_TRAGA,
    LJUBIMAC_JE_SRETNO_PRONAĐEN,
    LJUBIMAC_NIJE_PRONAĐEN_I_ZA_NJIM_SE_VIŠE_AKTIVNO_NE_TRAGA,
    LJUBIMAC_JE_PRONAĐEN_U_NESRETNIM_OKOLNOSTIMA,
    U_SKLONISTU

}
